name: CD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the source code
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      changelog: ${{ steps.tag_version.outputs.changelog }}

  github-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Checkout the source code
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.build.outputs.new_tag }}
          release_name: Release ${{ needs.build.outputs.new_tag }}
          body: ${{ needs.build.outputs.changelog }}

  npm-publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Checkout the source code
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set name
        run: git config --global user.name ${{ github.event.pusher.name }}

      - name: Set email
        run: git config --global user.email ${{ github.event.pusher.email }}

      - name: Update package version
        run: npm version ${{ needs.build.outputs.new_tag }}

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

  github-publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Checkout the source code
      - name: Checkout
        uses: actions/checkout@v2

      - name: Point to GitHub Packages
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com/

      - name: Set name
        run: git config --global user.name ${{ github.event.pusher.name }}

      - name: Set email
        run: git config --global user.email ${{ github.event.pusher.email }}

      - name: Update package version
        run: npm version ${{ needs.build.outputs.new_tag }}

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
